version: '3.8'
services:
  livekit-agent:
    build: .
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - N8N_MCP_SERVER_URL=${N8N_MCP_SERVER_URL}
      - TAVUS_API_KEY=${TAVUS_API_KEY}
      - REPLICA_ID=${REPLICA_ID}
      - PERSONA_ID=${PERSONA_ID}
    command: python agent.py start
    restart: unless-stopped
    
  token-server:
    build: .
    ports:
      - "5001:5001"
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
    command: python server.py
    restart: unless-stopped
